### ISSUE TITLE
Overlapping text lables

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#57] opened 2019-04-09 18:36 UTC
Text Labels overlaps the the values of select input.
_Tested on :_ Chrome, Firefox.

**Comment by MrClemRkz** [comment] 2019-04-24 19:28
Well this is a known-bug on material-UI -> https://github.com/mui-org/material-ui/issues/13186

Possible work-arounds for this are:
1) Having default state value which is not a 'null'
- tried empty string and **fails** in the scenario, sqlalchemy validates the value with field integer.
- tried with 0 (int), yet it **fails** where field is a foreign key, and thus fails 'foreign key constraint'.

Therefore either json should be manipulated as empty strings in null form OR change the incoming json validated as pass values as required.

2) Capture the change of the select input and set css props as "shrink={true}" on the InputLabel to have the label set on top. "shrink={false}" is the default value. Also the InputLabel and Select are two react components.
- Not tested yet.

**_Suggestions welcome_**

**Comment by ManZzup** [comment] 2019-07-02 14:08
Duplicate of #68

**Closed by ManZzup** 2019-07-02 14:08 UTC
Labels: bug, high
